===================================
Test for "100-lazy_matrix_mul.py" module
===================================

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
array([[ 7, 10],
       [15, 22]])

>>> lazy_matrix_mul([[1, 2, 3], [4, 5, 6]], [[7, 8], [9, 10], [11, 12]])
array([[ 58,  64],
       [139, 154]])

>>> lazy_matrix_mul([[1, 2]], [[3], [4]])
array([[11]])

>>> lazy_matrix_mul([[1]], [[2]])
array([[2]])

>>> lazy_matrix_mul([], [[1, 2], [3, 4]])
Traceback (most recent call last):
    ...
ValueError: shapes (1,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

>>> lazy_matrix_mul([[1, 2], [3, 4]], [])
Traceback (most recent call last):
    ...
ValueError: shapes (2,2) and (1,0) not aligned: 2 (dim 1) != 1 (dim 0)

>>> lazy_matrix_mul([[1, '2'], [3, 4]], [[5, 6], [7, 8]])
Traceback (most recent call last):
    ...
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[5, 6]])
Traceback (most recent call last):
    ...
ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

>>> lazy_matrix_mul([[1, 2], [3, 4, 5]], [[5, 6], [7, 8], [9, 10]])
Traceback (most recent call last):
    ...
TypeError: setting an array element with a sequence.

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[5, 6], [7]])
Traceback (most recent call last):
    ...
TypeError: setting an array element with a sequence.

>>> lazy_matrix_mul("not a list", [[1, 2], [3, 4]])
Traceback (most recent call last):
    ...
TypeError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul([[1, 2], [3, 4]], "not a list")
Traceback (most recent call last):
    ...
TypeError: Scalar operands are not allowed, use '*' instead

>>> lazy_matrix_mul([[1, 2], [3, 4]])
Traceback (most recent call last):
    ...
TypeError: lazy_matrix_mul() missing 1 required positional argument: 'm_b'

>>> lazy_matrix_mul()
Traceback (most recent call last):
    ...
TypeError: lazy_matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'

>>> lazy_matrix_mul([1, 2, 3], [[1, 2], [3, 4]])
Traceback (most recent call last):
    ...
TypeError: m_a must be a list of lists

>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, '2'], [3, 4]])
Traceback (most recent call last):
    ...
TypeError: invalid data type for einsum

>>> lazy_matrix_mul([[1, 2], [3, 4]], [5, 6, 7, 8])
Traceback (most recent call last):
    ...
TypeError: m_b must be a list of lists
